services:

  web:   
    build:
      context: . 
    volumes:
      - .:/app 
    env_file:
      - .env 
    depends_on:
      - db 

  db:
    image: postgres:15 
    env_file:
      - .env 
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432" 

  nginx:
    image: nginx:latest
    ports: 
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d 
    depends_on:
      - web

volumes:
  postgres_data: 